version: "3.9"
services:
  web:
    build: .
    container_name: browser
    restart: always
    ports:
      - 80:3000
    volumes:
      - ./:/home/browser
    environment:
      NODE_ENV: "production"