version: "3.9"
services:
  web:
    build: .
    container_name: browser
    restart: always
    ports:
      - 80:3000
    volumes:
      - ./:/home/browser
    environment:
      NODE_ENV: "production"
      NEXTAUTH_SECRET: 4815162342
      NEXT_PUBLIC_GITHUB_ID: <github_id>
      NEXT_PUBLIC_GITHUB_SECRET: <github_secret>
      NEXT_PUBLIC_MONGODB_URI: <database>